version: "3.3"

services:

  php:
    build:
      context: .
      dockerfile: ./build/php/DockerFile
    networks:
      - negs
    volumes:
      - ./:/var/www/negs
    working_dir: /var/www/negs

  nginx:
    build:
      context: .
      dockerfile: ./build/nginx/DockerFile
    depends_on:
      - php
    ports:
      - 82:80
    networks:
      negs:
        aliases:
          - 'pfa-test.local'
    working_dir: /var/www/negs
    volumes:
      - ./:/var/www/negs
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ne2_profiles'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - pfa-db:/var/lib/mysql

  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
      - nginx
    environment:
      HUB_HOST: hub
    networks:
      - negs

  hub:
    image: selenium/hub:3.14.0-gallium
    networks:
      - negs

volumes:
  pfa-db:

networks:
  negs:
