export enum RoutesEnum {
  PROFILES = 'profiles',
  ASSESSMENTS = 'assessments',
  FEEDBACK = 'feedback',
  PROFILES_ADD = 'profiles-add',
  ASSESSMENTS_ADD = 'assessments-add',
  FEEDBACK_ADD = 'feedback-add',
  QUESTIONS = 'questions',
  KEYS = 'keys',
  PARTICIPANTS = 'participants',
  IMPORT_PARTICIPANTS = 'import-participants',
  REPORTS = 'reports',
  CONFIGURATION = 'configuration',
  TRAINING_COURSES = 'training-courses',
  USER_ADMIN = 'user-administration',
  LOGIN = 'log-in',
  WELCOME = 'welcome',
  PAGE_NOT_FOUND = 'page-not-found',
  CLIENTS = 'clients',
  UNSUBSCRIBE = 'unsubscribe'
}
